name: Build Rocket Chat and pack to Docker image master

on: [workflow_dispatch]

env:
  CI: true
  # MONGO_URL: mongodb://localhost:27017
  TOOL_NODE_FLAGS: --max_old_space_size=4096
  
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Github Info
        run: |
          echo "GITHUB_ACTION: $GITHUB_ACTION"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "github.event_name: ${{ github.event_name }}"
          cat $GITHUB_EVENT_PATH
      - name: Use Node.js 14.18.3
        uses: actions/setup-node@v3
        with:
          node-version: '14.18.3'

      - uses: actions/checkout@v3

      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
          
      
      - name: Build Docker image for tag
        #if: github.event_name == 'release'
        run: |
          npm install --save @google-cloud/storage
          
          #–êuthentication with service account credentials
          gcloud auth activate-service-account ${{ secrets.GCR_ACCOUNT }} --key-file=${{ secrets.GCR_KEY }}
          gcloud auth configure-docker
          
          
      
      
